### ISSUE TITLE
extending MetricFilterImpl fails

### ISSUE THREAD

**Issue by seprich** [kenshoo/metrics-play#61]
Extending the MetricFilterImpl exactly like in example in order to implements custom labelPrefix generates following compile error:
```
play.sbt.PlayExceptions$CompilationException: Compilation error[could not find implicit value for parameter mat: akka.stream.Materializer]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
```
Versions: Scala: 2.12.3  Play (sbt plugin): 2.6.3  (metrics-play: 2.6.2_0.6.1)

**Comment by mosheeshel** [comment]
Hi @seprich this sounds like a version compatibility compatibility issue, @rannisim / @effiban  can you take a look?

**Comment by seprich** [comment]
I got it to compile with following change:
```
class MyMetricsFilter @Inject() (metrics: Metrics)(implicit override val mat: Materializer, override val ec: ExecutionContext) extends MetricsFilterImpl(metrics)(mat, ec) {
  override def labelPrefix: String = "testing"
}
```
...too early to say if it otherwise works..
I am still a novice with scala, but I tried to make the constructor signature identical with the inherited class.

**Comment by seprich** [comment]
IMO you should make labelPrefix settable from configuration.
