### ISSUE TITLE
 1) Error injecting constructor, java.lang.IllegalArgumentException: A metric named jvm.attribute.vendor already exists [info]   at com.kenshoo.play.metrics.MetricsImpl.<init>(Metrics.scala:28) [info]   at com.kenshoo.play.metrics.MetricsImpl.class(Metrics.scala:28)

### ISSUE THREAD

**Issue by ed1286** [kenshoo/metrics-play#85]
Hello I have encountered this error when doing a play 2.8 upgrade. I have seen the previous thread about this but it was quite outdated so wanted to bump a new one. Any ideas on how to resolve this would be greatly appreciated thanks :)

**Comment by tzachz** [comment]
Hi Edward, thanks for posting this issue!

I'm not aware of any relevant change so I'd assume the advice given on #74 is still relevant - gauge name uniqueness is a Metrics limitation which pops up when trying to re-register a metrics-play instance. If the instructions on that thread are insufficient - please provide some more information:

 - When do you see this error (when running tests? Starting the server?)
 - How are you instantiating MetricsPlay - are you using the default configuration (`play.modules.enabled+="com.kenshoo.play.metrics.PlayModule"`) or did you apply any customization?

**Comment by ed1286** [comment]
thanks for your response. I saw the issue when upgrading to Play 2.8. The advice on the thread was interesting, but out of the suggested solutions, the one he used isn't really an option for us, and the others don't apply as we don't/already do those things. 

-I see the error when doing sbt clean test compile
-play.modules.enabled+="com.kenshoo.play.metrics.PlayModule" is what we currently have in application.conf

Thanks :)
